package com.airsense.api.copilot;

public enum CopilotIntent {
    CURRENT_CONDITION,
    EXPLAIN_AQI,
    EXPLAIN_FORECAST,
    SOURCE_ATTRIBUTION,
    ENFORCEMENT_ACTION,
    CITIZEN_ADVISORY,
    DATASET_EVIDENCE,
    CONFIDENCE_EXPLANATION,
    PROVIDER_STATUS,
    TEMPORAL_COMPARISON,
    GEOSPATIAL_RISK,
    GENERAL_PLATFORM_HELP,
    UNSUPPORTED
}
