package com.airsense.api.geospatial;

public enum GeoSpatialLayerType {
    AQI_HOTSPOTS,
    FORECAST_GRID_24H,
    FORECAST_GRID_48H,
    FORECAST_GRID_72H,
    POLLUTION_SOURCE_ZONES,
    TRAFFIC_CORRIDORS,
    CONSTRUCTION_SITES,
    INDUSTRIAL_ZONES,
    SENSITIVE_ZONES,
    WIND_VECTOR_LAYER,
    GREEN_COVER_LAYER,
    SATELLITE_EVIDENCE_LAYER
}
