package com.airsense.api.enforcement;

public enum EnforcementActionType {
    INDUSTRIAL_INSPECTION,
    CONSTRUCTION_DUST_CONTROL,
    TRAFFIC_DIVERSION,
    ROAD_DUST_WATER_SPRINKLING,
    WASTE_BURNING_INSPECTION,
    SCHOOL_OUTDOOR_ACTIVITY_RESTRICTION,
    HEALTH_DEPARTMENT_ALERT,
    PUBLIC_ADVISORY,
    GREEN_BUFFER_ACTION,
    MONITORING,
    NO_ACTION_REQUIRED
}
