server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI}

server.forward-headers-strategy=framework
server.tomcat.threads.min-spare=2
spring.data.mongodb.auto-index-creation=false
server.tomcat.threads.max=25
server.tomcat.accept-count=25

